---
title: "Data Manipulation"
output: github_document
---

```{r setup}
library(tidyverse)

```

## Load the FAS_litters data
```{r}
litters_df=read_csv("./data/FAS_litters.csv")
litters_df=janitor::clean_names(litters_df)
litters_df
```

##`select`

choose some columns form the dataframe. 
```{r}
select(litters_df, group, litter_number, gd0_weight:gd_of_birth)
#use the ":" to select a range of columns 

select(litters_df, -litter_number)
#get rid of "litter_number only"
```

Renaming: 

```{r}
select(litters_df, GROUP=group, LITTER_NUM=litter_number)

#Or rename without select in dplyr: 
rename(litters_df, GROUP=group, LITTER_NUM=litter_number)
```

Select helper

```{r}
select(litters_df, starts_with("gd"))

select(litters_df, litter_number, everything())
#left everything except litter_number

relocate(litters_df, litter_number)
```

##`filter`
```{r}
filter(litters_df, gd0_weight <= 22)

filter(litters_df, !(gd0_weight == 20))
#"!" to filter out gd0_weight = 20

filter(litters_df, group == "Con8")

filter(litters_df, group %in% c("Con7", "Con8"))

```

##`mutate`

add new variable. change new variable.
```{r}
mutate(litters_data,
  wt_gain = gd18_weight - gd0_weight,
  group = str_to_lower(group)
)
```

##`arrange`
```{r}
head(arrange(litters_data, group, pups_born_alive), 10)
```


##%>%

press ctrl+shift+m to indsert pipe command %>% 
you can call the %>% "and then"